version: "3.7"
services:
#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - .:/app
#      - /app/node_modules
#    restart: always
#    environment:
#      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DATABASE}?schema=public
#      NODE_ENV: ${NODE_ENV}
#    command: npm run start:dev
#    ports:
#      - "${API_PORT}:${API_PORT}"
#    depends_on:
#      - postgres
#    networks:
#      - music-network
  postgres:
    env_file: .env
    container_name: postgres
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    volumes:
      - docker-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - music-network
  postgres-test:
    env_file: .env.test
    container_name: postgres-test
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - docker-postgres-test:/var/lib/postgresql/data
    ports:
      - "5433:5432" # порт для тестовой базы данных
    networks:
      - music-network
volumes:
  docker-postgres:
  docker-postgres-test:
networks:
  music-network: